[workspace]
resolver = "3"
members = ["vizual", "vizual-configurator", "vizual-macros"]

[workspace.lints.rust]
non_camel_case_types = "allow"
non_upper_case_globals = "allow"
unused_must_use = "warn"
unused_results = "warn"

# Optimizing MicroLP makes the layout solver about 10 times faster in development builds.
[profile.dev.package.microlp]
opt-level = 3
