[package]
name = "vizual-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
ambassador = "0.5.0"
vizual = { path = "../vizual" }
vizual-macros = { path = "../vizual-macros" }
arc-swap = "1.7.1"
async-trait = "0.1.89"
color-eyre = "0.6.5"
tokio = { version = "1.47.1", features = ["full"] }
regex = "1.11.3"
uniqify = "0.1.0"
derive-new = "0.7.0"
dyn-clone = "1.0.20"
lucide-icons = "1.28.0"

[lints]
workspace = true
