[package]
name = "vizual-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for the Vizual UI framework"
repository = "https://github.com/ElectricPulse/vizual"
license = "Apache-2.0"
categories = ["gui", "development-tools::procedural-macro-helpers"]
keywords = ["gui", "ui", "macros", "derive", "vizual"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }

[lints]
workspace = true
