[package]
name = "drevo"
version = "0.1.6"
edition.workspace = true
description = "An async, solver-driven desktop UI framework rendered with Vello"
repository.workspace = true
license.workspace = true
readme.workspace = true
categories = ["gui", "rendering", "asynchronous"]
keywords = ["gui", "ui", "layout", "vello", "solver"]

[dependencies]
derive-where.workspace = true
ambassador = "0.5.0"
async-trait = "0.1.89"
drevo-macros = { version = "0.1.3", path = "../drevo-macros" }
tokio = { version = "1.48.0", features = ["full"] }
color-eyre = "0.6.5"
derive-new = "0.7.0"
delegate = "0.13.5"
dyn-clone = "1.0.20"
async-recursion = "1.1.1"
futures = "0.3.32"
highs = "2.4.0"
highs-sys = "1.15.0"
log = "0.4.29"
simplelog = "0.12.2"
time = { version = "0.3.47", features = ["formatting"] }
uuid = { version = "1.23.1", features = ["v4"] }
unit-intervals = "0.1.0"
parley = "0.11.0"
lucide-icons = "1.28.0"
skrifa = "0.42.1"
pollster = "1.0.1"
vello = "0.9.0"
winit = "0.30.12"
path-clean = "1.0.1"
replace-homedir = "0.1.1"

[lints]
workspace = true
